image: node:6.9


test:
  cache:
    paths:
      - .yarn-cache
      - yarn.lock

  script:
    - id
    - python --version
    - type node; node -v

    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - mkdir -p .yarn-cache

    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
    - apt-get update --yes && apt-get install --yes libfreetype6 libfontconfig
    - export PATH=`yarn bin`:$PATH

    - yarn install --cache-folder .yarn-cache
    - bower install --allow-root
    - ember build --env=production
    - set -o pipefail; ember test | grep -v ^ok
    #- ember test --reporter=xunit |tail -1 > shippable/testresults/result.xml
    #- python lcov_cobertura.py lcov.dat -o shippable/codecoverage/coverage.xml

